name: Update GitHub Snake

on:
  schedule:
    - cron: "0 3 * * *"
  push:
    paths:
      - ".github/workflows/github-snake.yml"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Generate GitHub Snake
        uses: Platane/snk@v3
        with:
          github_user_name: nolanheriniaina
          outputs: |
            profile/github-snake.svg
            profile/github-snake-dark.svg?palette=github-dark

      - name: Commit generated files
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"

          git add profile/github-snake.svg profile/github-snake-dark.svg

          git diff --cached --quiet && exit 0

          git commit -m "Update GitHub Snake"
          git push
